# Generated by Django 3.1.6 on 2022-06-22 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_alter_profile_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('tag', models.CharField(max_length=300)),
                ('company', models.CharField(max_length=100)),
                ('detail', models.CharField(max_length=1000)),
                ('qualification', models.CharField(max_length=300)),
                ('award', models.CharField(max_length=100)),
                ('field', models.CharField(max_length=300)),
                ('apply_url', models.CharField(max_length=300)),
                ('img_url', models.CharField(blank=True, max_length=300)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
