# Generated by Django 3.1.6 on 2022-06-22 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contest', '0002_auto_20220622_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='author',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='contest', to=settings.AUTH_USER_MODEL),
        ),
    ]
