# Generated by Django 3.1.6 on 2022-06-23 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_profile_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('company', models.IntegerField()),
                ('detail', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('applyperiod', models.DateField()),
                ('actperiod', models.DateField()),
                ('author', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='volunteer', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
