# Generated by Django 3.1.6 on 2022-06-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0002_auto_20220623_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='location',
            field=models.CharField(max_length=200),
        ),
    ]
