# Generated by Django 3.1.6 on 2022-06-08 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_alter_profile_age'),
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='actperiod',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='apply_period',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='apply_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='author',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='company',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='activity',
            name='detail',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='activity',
            name='field',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='activity',
            name='img_url',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='activity',
            name='likes',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='personnel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activity',
            name='profile',
            field=models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AddField(
            model_name='activity',
            name='tag',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='title',
            field=models.CharField(default='', max_length=300),
        ),
    ]
