# Generated by Django 3.1.6 on 2022-06-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20220608_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='company',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='activity',
            name='tag',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
