# Generated by Django 3.1.6 on 2022-06-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_auto_20220623_0920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='activity',
            name='field',
        ),
        migrations.AddField(
            model_name='activity',
            name='field',
            field=models.ManyToManyField(blank=True, null=True, to='activity.Field'),
        ),
        migrations.RemoveField(
            model_name='activity',
            name='tag',
        ),
        migrations.AddField(
            model_name='activity',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='activity.Tag'),
        ),
    ]
