# Generated by Django 3.1.6 on 2022-06-20 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20220620_2152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='author',
            new_name='user',
        ),
    ]
