# Generated by Django 3.1.6 on 2022-06-22 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20220620_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='file_upload',
            field=models.FileField(blank=True, upload_to='portfolio/file/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='head_img',
            field=models.ImageField(blank=True, upload_to='portfolio/img/'),
        ),
    ]
