# Generated by Django 3.1.6 on 2022-06-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=30)),
                ('personnel', models.IntegerField()),
                ('content', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
