# Generated by Django 3.1.6 on 2022-06-22 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_auto_20220620_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='name',
        ),
    ]
